services:
  db:
    image: postgres
    restart: unless-stopped
    env_file:
      - database.env
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "$POSTGRES_USERNAME", "-U", "$POSTGRES_PASSWORD" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
