  name: 🚀 Сборка и деплой в Yandex Cloud

on:
  # Автоматические триггеры для деплоя
  push:
    branches:
      - master    # Продовый стенд
      - staging   # Тестовый стенд
  # Ручной запуск
  workflow_dispatch:
    inputs:
      environment:
        description: 'Куда деплоить?'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production
      image-tag:
        description: 'Версия образа (например: v1.0.0)'
        required: false
        default: 'latest'
        type: string
      build-image:
        description: 'Собирать образ при отсутствии?'
        required: false
        default: true
        type: boolean

# Контроль конкурентных запусков
concurrency:
  group: deploy-${{ github.ref_name }}-${{ github.event.inputs.environment || github.ref_name }}
  cancel-in-progress: true

env:
  APP_NAME: "partners-microservice"
  HELM_CHART_REPO: "https://github.com/Academic-Mobility-Center/helm-charts.git"
  HELM_CHART_NAME: "partners-microservice"
  REGISTRY: "cr.yandex/crphujqn4a371i0ve0b5"
  DOCKERFILE_PATH: "./src/StudMart.PartnersMicroservice/Presentation/StudMart.PartnersMicroservice.Presentation.WebHost/Dockerfile"
  CONTEXT_PATH: "./src/StudMart.PartnersMicroservice"
  # Определяем окружение: для автоматических запусков по веткам, для ручных - из параметров
  K8S_NAMESPACE: ${{ github.event.inputs.environment || (github.ref_name == 'master' && 'production') || 'staging' }}
  # Тег образа: для автоматических запусков используем SHA коммита, для ручных - из параметров
  IMAGE_TAG: ${{ github.event.inputs.image-tag || github.sha }}
  VALUES_FILE: "values.${{ github.event.inputs.environment || (github.ref_name == 'master' && 'production') || 'staging' }}.yaml"

jobs:
  # Запуск тестов (если они есть)
  test:
    name: 🧪 Запуск тестов
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: 🛠 Загрузка кода
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🔧 Установка .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: 🔍 Поиск тестовых проектов
        id: find-tests
        run: |
          TEST_PROJECTS=$(find . -name "*.Tests.csproj" -o -name "*Test*.csproj" | tr '\n' ' ')
          if [ -n "$TEST_PROJECTS" ]; then
            echo "test-projects=$TEST_PROJECTS" >> $GITHUB_OUTPUT
            echo "has-tests=true" >> $GITHUB_OUTPUT
            echo "✅ Найдены тестовые проекты: $TEST_PROJECTS"
          else
            echo "has-tests=false" >> $GITHUB_OUTPUT
            echo "ℹ️ Тестовые проекты не найдены"
          fi

      - name: 🧪 Запуск тестов
        if: steps.find-tests.outputs.has-tests == 'true'
        run: |
          echo "🧪 Запускаю тесты..."
          dotnet test ${{ steps.find-tests.outputs.test-projects }} --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./TestResults

      - name: 📊 Публикация результатов тестов
        if: always() && steps.find-tests.outputs.has-tests == 'true'
        uses: dorny/test-reporter@v1
        with:
          name: .NET Tests
          path: ./TestResults/**/*.trx
          reporter: dotnet-trx

  deploy:
    name: 🚀 Деплой ${{ github.event.inputs.image-tag || github.sha }} в ${{ github.event.inputs.environment || (github.ref_name == 'master' && 'production') || 'staging' }}
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || (github.ref_name == 'master' && 'production') || 'staging' }}
    needs: test
    if: always() && (needs.test.result == 'success' || needs.test.result == 'skipped')
    
    steps:
      - name: 📌 Подготовка
        id: preparation
        run: |
          echo "🚀 Начало деплоя ${{ env.APP_NAME }}"
          echo "👤 Инициатор: ${{ github.actor }}"
          echo "🏷 Версия образа: ${{ env.IMAGE_TAG }}"
          echo "🌍 Окружение: ${{ env.K8S_NAMESPACE }}"
          echo "📝 Файл конфигурации: ${{ env.VALUES_FILE }}"
          echo "🛠 Сборка при отсутствии образа: ${{ github.event.inputs.build-image || 'true' }}"
          echo "🐳 Dockerfile: ${{ env.DOCKERFILE_PATH }}"
          echo "⏱ Начато в: $(date)"
          echo "🔖 Хеш коммита: ${{ github.sha }}"
          echo "🏷 Метка: ${{ github.ref_name }}"
          echo "🔄 Тип запуска: ${{ github.event_name == 'push' && 'Автоматический' || 'Ручной' }}"
          echo "📋 Ветка: ${{ github.ref_name }}"

          echo "start-time=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT

      - name: 🛠 Загрузка кода приложения
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 📦 Загрузка Helm-чартов
        uses: actions/checkout@v4
        with:
          repository: Academic-Mobility-Center/helm-charts
          token: ${{ secrets.GH_TOKEN }}
          path: helm-chart

      - name: 🔍 Проверка наличия values файла
        run: |
          echo "Проверяю наличие файла конфигурации: ${{ env.VALUES_FILE }}"
          if [ ! -f "helm-chart/charts/${{ env.HELM_CHART_NAME }}/${{ env.VALUES_FILE }}" ]; then
            echo "::error::Файл конфигурации ${{ env.VALUES_FILE }} не найден!"
            exit 1
          else
            echo "✅ Файл конфигурации найден"
          fi

      - name: 🐳 Настройка Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 🔐 Авторизация в Yandex Container Registry
        uses: yc-actions/yc-cr-login@v2
        with:
          yc-sa-json-credentials: ${{ secrets.YC_CI_REGISTRY_PASSWORD }}

      - name: 🔍 Проверка существования образа
        id: image-check
        run: |
          echo "🔍 Проверяю наличие образа в реестре..."
          IMAGE="${{ env.REGISTRY }}/${{ env.APP_NAME }}:${{ env.IMAGE_TAG }}"
          
          if docker manifest inspect $IMAGE > /dev/null 2>&1; then
            echo "✅ Образ уже существует в реестре"
            echo "image-exists=true" >> $GITHUB_OUTPUT
          else
            echo "⚠️ Образ не найден в реестре"
            echo "image-exists=false" >> $GITHUB_OUTPUT
          fi

      - name: 🏗️ Сборка Docker образа
        if: steps.image-check.outputs.image-exists == 'false' && (github.event.inputs.build-image != 'false')
        run: |
          echo "🏗️ Начинаю сборку Docker образа..."
          echo "📦 Имя образа: ${{ env.REGISTRY }}/${{ env.APP_NAME }}:${{ env.IMAGE_TAG }}"
          echo "📂 Путь к Dockerfile: ${{ env.DOCKERFILE_PATH }}"
          
          BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          GIT_SHA=$(git rev-parse HEAD)
          GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          
          echo "::group::🚀 Выполнение сборки Docker"
          docker buildx build \
            -t "${{ env.REGISTRY }}/${{ env.APP_NAME }}:${{ env.IMAGE_TAG }}" \
            -t "${{ env.REGISTRY }}/${{ env.APP_NAME }}:latest" \
            --build-arg BUILD_VERSION=${{ env.IMAGE_TAG }} \
            --build-arg BUILD_DATE=$BUILD_DATE \
            --build-arg GIT_COMMIT=$GIT_SHA \
            --build-arg GIT_BRANCH=$GIT_BRANCH \
            --progress plain \
            --push \
            -f ${{ env.DOCKERFILE_PATH }} ${{ env.CONTEXT_PATH }}
          
          BUILD_STATUS=$?
          echo "::endgroup::"
          
          if [ $BUILD_STATUS -ne 0 ]; then
            echo "::error::❌ Сборка Docker образа завершилась с ошибкой"
            exit 1
          fi
          
          echo "image-built=true" >> $GITHUB_OUTPUT
          echo "✅ Образ успешно собран и отправлен"
          
  
      - name: ⚙️ Установка Helm
        uses: azure/setup-helm@v4.3.0

      - name: Create kubeconfig
        run: |
          mkdir ${HOME}/.kube
          echo ${{ secrets.YC_KUBE_CONFIG }} | base64 --decode > ${HOME}/.kube/config
          kubectl config use-context default

      - name: 🚀 Деплой с помощью Helm
        id: helm-deploy
        run: |
          echo "🚀 Начинаю деплой с Helm..."
          echo "👤 Инициатор: ${{ github.actor }}"
          echo "📌 Целевой неймспейс: ${{ env.K8S_NAMESPACE }}"
          echo "🏷 Версия образа: ${{ env.IMAGE_TAG }}"
          echo "📝 Использую конфигурацию: ${{ env.VALUES_FILE }}"
          echo "🔄 Тип запуска: ${{ github.event_name == 'push' && 'Автоматический' || 'Ручной' }}"
          
          echo "::group::🚀 Выполнение Helm деплоя"
          helm upgrade --install ${{ env.APP_NAME }} ./helm-chart/charts/${{ env.HELM_CHART_NAME }} \
            --namespace ${{ env.K8S_NAMESPACE }} \
            --create-namespace \
            --values ./helm-chart/charts/${{ env.HELM_CHART_NAME }}/${{ env.VALUES_FILE }} \
            --set image.tag=${{ env.IMAGE_TAG }} \
            --set image.repository=${{ env.REGISTRY }}/${{ env.APP_NAME }} \
            --set ci.build.enabled=${{ github.event.inputs.build-image != 'false' }} \
            --set image.verify=true \
            --wait \
            --timeout 5m \
            --atomic \
            --debug
          
          HELM_STATUS=$?
          echo "::endgroup::"
          
          if [ $HELM_STATUS -ne 0 ]; then
            echo "::error::❌ Деплой Helm завершился с ошибкой"
            exit 1
          fi
          
          echo "deployment-status=success" >> $GITHUB_OUTPUT
          echo "✅ Деплой успешно завершен"

      - name: 📊 Проверка деплоя
        if: always()
        run: |
          echo "🔍 Проверяю состояние деплоя..."
          kubectl rollout status deployment/${{ env.APP_NAME }} -n ${{ env.K8S_NAMESPACE }} --timeout=120s || true
          
          echo ""
          echo "📊 Детали деплоя:"
          kubectl describe deployment/${{ env.APP_NAME }} -n ${{ env.K8S_NAMESPACE }} | head -n 20

      - name: 📝 Итоговый отчет
        if: always()
        run: |
          echo "🏁 Процесс деплоя завершен"
          echo "👤 Инициатор: ${{ github.actor }}"
          echo "🔄 Тип запуска: ${{ github.event_name == 'push' && 'Автоматический' || 'Ручной' }}"
          echo "📋 Ветка: ${{ github.ref_name }}"
          echo "⏱ Длительность: $(( ($(date +%s) - $(date -d "${{ steps.preparation.outputs.start-time }}" +%s)) / 60 )) минут"
          echo "🔄 Состояние образа: ${{ steps.image-check.outputs.image-exists == 'true' && 'Существующий' || 'Новый' }}"
          echo "🚀 Статус деплоя: ${{ job.status }}"
          echo "📝 Использованная конфигурация: ${{ env.VALUES_FILE }}"
          echo "🧪 Статус тестов: ${{ needs.test.result || 'Не запускались' }}"
          
          if [ "${{ job.status }}" = "success" ]; then
            echo "✅ Деплой успешно завершен!"
            echo "::notice::Деплой успешно завершен"
          else
            echo "❌ Деплой завершен с ошибкой"
            echo "::error::Деплой завершен с ошибкой"
          fi

          
